server:
  port: 8030
spring:
  application:
    name: gateway
eureka:
  client:
    service-url:
    defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    serviceProvider: /p/**
#给服务提供者provider设置映射。