server:
  port: 8060
spring:
  application:
    name: hystrix
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'
feign:
  hystrix:
    enabled: true
